server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: file:/app/uploads/

jwt:
  secret: MySuperSecretKeyForJwt12345678901234567890123456789012
  expiration-ms: 21600000
  refresh-expiration-ms: 604800000

qr:
  token:
    secret: E5zYwR1Xdpz8TqLnaU2cVsHxPvKqJGbf
    expiration: 604800000

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}

app:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:https://waitero-front.vercel.app}
